version: "3"
services:

  app:
    image: openjdk:11-slim
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - "./app/build/libs/spring-0.0.1-SNAPSHOT.jar:/tmp/spring-0.0.1-SNAPSHOT.jar"
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /tmp/spring-0.0.1-SNAPSHOT.jar"

  db:
    image: library/postgres:13.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/initdb:/docker-entrypoint-initdb.d"